[package]
name = "kurit-ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core.workspace = true
tokio.workspace = true
markdown = "1.0.0-alpha.14"